// <auto-generated />
using AjaxDragAndDropExample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AjaxDragAndDropExample.Migrations
{
    [DbContext(typeof(AjaxDbContext))]
    [Migration("20221204021005_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AjaxDragAndDropExample.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Mustafa DOĞAN"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Ali DOĞAN"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Abdullah DOĞAN"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Rıza DOĞAN"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Salih DOĞAN"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Emre DOĞAN"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Bulut DOĞAN"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Polat DOĞAN"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Memati DOĞAN"
                        });
                });

            modelBuilder.Entity("AjaxDragAndDropExample.Models.CustomerRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CustomerRooms");
                });

            modelBuilder.Entity("AjaxDragAndDropExample.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomName = "101",
                            RoomTypeID = 2
                        },
                        new
                        {
                            Id = 2,
                            RoomName = "102",
                            RoomTypeID = 3
                        },
                        new
                        {
                            Id = 3,
                            RoomName = "103",
                            RoomTypeID = 2
                        },
                        new
                        {
                            Id = 4,
                            RoomName = "104",
                            RoomTypeID = 4
                        });
                });

            modelBuilder.Entity("AjaxDragAndDropExample.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomTypeName = "Tekli Oda"
                        },
                        new
                        {
                            Id = 2,
                            RoomTypeName = "2'li Oda"
                        },
                        new
                        {
                            Id = 3,
                            RoomTypeName = "3'lü Oda"
                        },
                        new
                        {
                            Id = 4,
                            RoomTypeName = "4'lü Oda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
